//oh_no
const categorylist = ['Acrobat','Adaptive_Arsenal','Adept_Caster','Aerial_Dancer','Aeromancer','Alchemist','Alley_Cat','All-Knowing','Amoran_Seeker','Angler','Annihilator','Apex_Predator','Artisan','Assassin','Athlete','Authority_Interrogator','Bastion','Blindseer','Berserker','Bloodhound','Bloodrender','Bloodsong','Brawler','Bruiser','Bulwark','Butterfly','Champion','Charm_Caster','Christmas_Miracle','Cold_Phantom','Colossus','Comrade','Cosmic_Wind','Critical_Specialist','Cryomancer','Cryonic','Cutthroat','Darksiphon','Dawnwalker','Death_Speaker','Deepwoken','Doomsday_Engine','Duelist','Pursuer','Duelist_Flame','Elementalist','Empath','Escape_Artist','Ether_Adept','Falling_Star_Guard','Fang_and_Coil','Fish','Flame_Dancer','Flame_Warden','Flamecharmer','Flashfreeze','Freak_Of_Nature','Frost_Forger','Frostdrawer','Frozen_Lightning','Frostthorn','Frozen_Warrior','Gale_Duelist','Gale_Kata','Galebreather','Galeforce','Genius_Intellect','Glassdancer','Great_Wall','Gunslinger','Hammer_Rage','Heat_Column','Heretic','Human_Architecture','Hunter','Ice_Age','Immolator','Inferno','Ironsinger','Iron_Will','Javelin_Lord','Jetstriker','Justicar','Kickstarter','Lancer','Lava_Serpent','Leader','Leaf_in_the_Wind','Legion_Shock_Trooper','Liberator','Lichtenberg','Limitbreaker','Marauder','Master_Survivalists','Meditative_Trance','Mental_Fortress','Merchant','Metallurgist','Metamancer','Ministry_Prophet','Mindbreaker','Mr_Charm','Murmur','Natural_Armor','Navaen_Nomad','Needle','Nimble_Blade','Omniscient','One_Eyed_King','Outlaw','Politician','Prospector','Public_Figure','Pyroclast','Pyromancer','Quack_Doctor','Raging_Bull','Rampaging_Brute','Rampant_Static','Rending_Needle','Saboteur','Sage_of_Wisps','Saint_of_Blades','Sapper','Scarlet_Donor','Scholar_of_the_Cloud','Scoundrel','Scrapsinger','Seeker_of_Sound','Self-Shocker','Septicemia','Shadowcast_Master','Shadowcaster','Shieldmaster','Shipwright','Silencer','Silvertongue','Showboater','Soul_Converter','Soverign_of_Slaughter','Specter','Spoils_of_Enmity','Static_Weaver','Stormcaller','Sturdy_Resolve','Super_Conductor','Survival_Instinct','Survivor','Swiftshade','Tactician','Tamed_Flame','Tavernkeep','The_Demon_Blade','The_Emperors_Blade','The_Negotiator','Thief','Thunder_Brawler','Thunder_Caster','Thunderblade','Thundercaller','Toxic_Personality','Transitory_Vitality','Trickster','Twinblade','Twisted_Puppets','Tyrant','Undying_Ember','Unstable_Capacitor','Vigil_Swordsman','Visionshaper','Vocalist','Vow_of_Mastery','Warrior','Waterborne','Weapon_Master','Whisper','Windrunner'];
const hi = document.createElement("div");
for (var i = 0; i < categorylist.length; i++) {
    let hi2 = document.createTextNode(categorylist[i]);
    let w = document.createElement("br");
    hi.appendChild(hi2);
    hi.appendChild(w);
    document.getElementById("talentbox1").appendChild(hi);
};
